name: dart_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.3.1
  # mysql1: ^0.20.0
  dart_jsonwebtoken: ^2.6.2
  envied: ^0.3.0
  envify: ^2.0.2
  mysql_client: ^0.0.27
  orm: ^2.4.5
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  

dev_dependencies:
  build_runner: ^2.3.2
  envied_generator: ^0.3.0
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0

prisma:
    schema: prisma/schema.prisma # Path to your Prisma schema
    production: lib/prisma_configurator.dart # Path to your production configurator
    development: prisma/development.dart # Path to your development configurator

